### ISSUE TITLE
Integrate ESLint for Consistent Indentation

### ISSUE THREAD

**Issue by soniasingla** [shardeum/shardeum#24]
### Description

There are several instances in the codebase where indentation is inconsistent. Some blocks of code are indented with 2 spaces, while others are indented with 4. This inconsistency makes the code harder to read and understand.

### Expected outcome

By integrating ESLint with TypeScript support, all blocks of code should be consistently indented, with 4 spaces.

### Suggested fix

Start by adding ESLint to the project. Instead of overwhelming the entire codebase at once, we'll gradually add ESLint rules file by file. You can read more about integrating ESLint to the project [here](https://eslint.org/docs/latest/use/getting-started).

Please ensure that indentation is set to 4 spaces throughout the codebase.

To streamline this process, you can use the ESLint extension for Visual Studio Code: [ESLint Extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

**Comment by stinkymonkeyph** [comment]
If this is free I'd like to this task

**Comment by soniasingla** [comment]
@stinkymonkeyph feel free to take the task, if you run into any blockers, do not hesitate to ping me 🤗

**Comment by ktarun1419** [comment]
Hi i want to take this issue @soniasingla

**Comment by soniasingla** [comment]
@ktarun1419 Hi, yes i am going to assign this issue to you and if you have any questions, feel free to ask in the comments 🌟

**Comment by Dozie2001** [comment]
Noticed this issue is still open may I give it a try @soniasingla ?

**Comment by AjayiMike** [comment]
@soniasingla Kindly assign this to me if it's still open

**Comment by kokiy47** [comment]
goog

**Comment by soniasingla** [comment]
@AjayiMike the issue is still open, feel free to raise a PR

**Comment by falgunmpatel** [comment]
@soniasingla I think this can be handled with Prettier Configurations and a pre-commit hook (husky). ESLint will only warn for spaces maybe but not enforce it. And this must not be handled with ESLint but Prettier. 

Please explain me, if I  am wrong. No offence intended!!

**Comment by soniasingla** [comment]
@falgunmpatel i am gonna close this PR, since we already have the linting enabled. Feel free to check our codebase and create an issue if there is chance for improvement
