### ISSUE TITLE
Improve Instructions for Using `/*prettier-ignore*/` in CONTRIBUTING.md

### ISSUE THREAD

**Issue by soniasingla** [shardeum/shardeum#32]
## Description

Our CONTRIBUTING.md file mentions using `/*prettier-ignore*/` for long debug code lines, but it doesn't provide detailed guidance on when and how to use it. Let's make it easier for new contributors by adding some clear instructions.

## Tasks

1. Learn how `/*prettier-ignore*/` works in Prettier.
2. Add a new section to the CONTRIBUTING.md file titled "Using /*prettier-ignore*/".
3. Explain what `/*prettier-ignore*/` is and include examples of when and how to use it.
4. Make sure the explanation is clear and beginner-friendly.

## Resources

- [Prettier Documentation](https://prettier.io/docs/en/ignore.html)

**Comment by noob-coder-19** [comment]
Hi @soniasingla Can you assign me this?

**Comment by soniasingla** [comment]
@noob-coder-19 👋 I have assigned the issue to you, please do not hesitate to ping me if you run into any issues 🤗

**Comment by noob-coder-19** [comment]
Hi @soniasingla, as mentioned above in the instructions, in the CONTRIBUTING.md file, I have added a new section called Using /* prettier-ignore */. Under that I have added the following sections: 

1. What is `/* prettier-ignore */`?
2.  When to Use `/* prettier-ignore */`
3. How to Use `/* prettier-ignore */`
4. Best Practices when using `/* prettier-ignore */`

Is there anything further you believe should be included? If not, shall I proceed to creating the pull request?

**Comment by soniasingla** [comment]
@noob-coder-19 I believe it should cover everything, feel free to create a pull request and i will review 🎉
